### ISSUE TITLE
Save state for file:// protocol

### ISSUE THREAD

**Issue by PaulMaly** [visionmedia/page.js#529] opened 2018-12-26 00:52 UTC
Hi! Could you please give me advise, how to save a state when file:// protocol used? 

It seems, saving disable for this case, but I don't know which purpose of this. 
https://github.com/visionmedia/page.js/blob/bb44f10cb2e006b67645f2f37b4f889d7e2adffe/index.js#L711

Could you please explain why so? Thanks!

**Comment by matthewp** [comment] 2019-01-10 14:48
Unfortunately not. I think we need to figure out a better way to test file:// though. It's been a continued pain and regressions occur.  Did you try doing a `git blame` to see if that was added? Might be able to track down the issue.

**Comment by PaulMaly** [comment] 2019-01-23 16:57
@matthewp Seems, it was added by you here: https://github.com/visionmedia/page.js/commit/12e018964703dfaafe6ef1a5806d84a78615f8f4

I just need to understand is it really needed?

**Comment by PaulMaly** [comment] 2019-01-23 17:14
I've submitted two patches for this issue:

https://github.com/visionmedia/page.js/pull/530
https://github.com/visionmedia/page.js/pull/531

Could you please check them and merge to the master?

**Comment by PaulMaly** [comment] 2019-01-29 06:31
@matthewp Any news here? Sorry for my perseverance but it’s very important to me to stay in original repo.

**Comment by matthewp** [comment] 2019-01-29 11:52
Yeah sorry for the delay, looking now..

**Comment by matthewp** [comment] 2019-01-29 11:53
Ok, merged those two. Just looking to see if there are anything else to merge and then I'll do a release. Closing this issue since it's fixed.

**Closed by matthewp** 2019-01-29 11:53 UTC
Labels: file protocol, question
