### ISSUE TITLE
Updating to latest path-to-regexp breaks '*' matching...

### ISSUE THREAD

**Issue by andyburke** [visionmedia/page.js#115] opened 2014-07-08 21:43 UTC
```javascript
page( '*', function( context, next ) {
  console.log( 'this matched all routes' );
});
```

No longer works with latest path-to-regexp, you must specify an explicit regexp:

```javascript
page( /.*/, function( context, next ) {
  console.log( 'this will now really match all routes' );
});
```

**Comment by mbektimirov** [comment] 2015-01-30 07:57
This behavior doesn't represent in tests at all. The case `should invoke subsequent matching middleware` has `'/forum/*'`route defined on start, but doesn't check it.

**Comment by rstacruz** [comment] 2015-01-30 08:30
> I think, we should add link to path-to-regexp to docs. But if pagejs is "router inspired by the Express router" then should we use same path-to-regexp version as express?

:+1: on this one.

**Comment by shuvalov-anton** [comment] 2015-01-30 10:41
@rstacruz the problem is that now we use the last version of `path-to-regexp` and downgrade will broke some backward compatible with `page@1.6.0`'s routing.

**Comment by shuvalov-anton** [comment] 2015-04-06 19:48
What do you think about downgrade to `path-to-regexp@0.1.3` like express? I'm going to read changelog to get what we will lose with the downgrade. //cc @JonDum

**Comment by JonDum** [comment] 2015-04-06 20:00
I think [blakeembrey's](https://github.com/pillarjs/path-to-regexp/issues/37#issuecomment-53442290 reasoning) doesn't work for page.js's use case. He argues that transforming `/*` is limiting for advanced routing so he decided to not take that trade off.

I argue that, by default, that limitation (allowing `/users/*`) offers more simplicity in both route setup and for new users' understanding, which is in line with the spirit of page.js (not to mention it's been that way on the docs forever!). If a page.js user needs more advanced configuration where the asterisk transforming may not be wanted, then the user should switch to passing a regexp directly to the route and bypass pathtoregexp entirely. The docs could reflect this and it shouldn't be confusing.

Then the only question is whether to downgrade pathtoregexp, try to convince blake, or fork it? (ew?)

**Comment by shuvalov-anton** [comment] 2015-04-06 20:24
Oh, looks like the downgrade is breaking existed code too. We have few ways: go back to our own `path-to-regexp` code, update the docs to match `path-to-regexp@1.x` or downgrade it.

I prefer to document the current version of `path-to-regexp` because it is more flexible. For example, I'm using special characters in my paths like this:

```js
page('/topics/:id(\\d+)/', /* ... */);
page('/topics/:type?/new', /* ... */);
page('/topics/:type?', /* ... */);
```

**Comment by JonDum** [comment] 2015-04-08 15:16
@shuvalov-anton Is it possible to have named parameter parsing to ctx.params when passing in a regex directly?

**Comment by jcoffland** [comment] 2015-04-29 22:20
This really needs to be fixed one way or the other.  The docs say I can do this ```page('/user/*', load)``` but that does not work.  I really have to do this ```page('/user/(.*)', load)```.

**Comment by jcoffland** [comment] 2015-04-29 22:33
One option would be to require users to pass an actual regex object if they want to do a full regex.  Then you would have:

    page(/\/user\/(.*)/, load);

or

    page('/user/*', load);

page.js could then contain code like this:

```
if (!(path instanceof RegExp)) path = new RegExp(path.replace('*', '(.*)'));
```

The only problem is this breaks existing code like this:

    page('/user/(.*)', load);

But matching is broken anyway.  A workaround might be to check paths for ```()``` characters and assume these are already regular expressions.

**Comment by andineck** [comment] 2015-05-11 20:33
I use page.js in a isomorphic app. I would appreciate the downgrade approach and favour a simpler live for the users of page.js. regex is really not every ones favourite.

**Comment by mushishi78** [comment] 2015-08-09 22:09
Please update docs!

**Comment by gertsonderby** [comment] 2015-09-07 12:45
PathToRegexp v1.2.1 fixes this problem, is used by Express.

**Comment by woodlandhunter** [comment] 2015-10-15 16:15
page.js 1.6.4  incorporates path-to-regexp 1.2.1 which fixes the issue (`/user/*` style routes now work as expected) .

@shuvalov-anton Recommend closing this issue.

**Closed** 2015-10-16 13:09 UTC
Labels: docs, help wanted
