### ISSUE TITLE
when hash doesn't change, the callback function shouldn't be called

### ISSUE THREAD

**Issue by iamwelk** [visionmedia/page.js#366] opened 2016-03-31 02:26 UTC
here is my page options

``` javascript
page({
    hashbang: true
});
```

when I click the link which is same with current URL, the function bind to the URL will be called even if the URL has not changed. I think it's should be configured.
Wish your reply. Thank you~

**Comment by iandunn** [comment] 2017-07-28 21:56
It seems like this is a duplicate of #417 

(This is older, but #417 has more discussion, including a workaround)

**Comment by matthewp** [comment] 2018-01-13 02:07
Thanks @iandunn! Let's discuss in #477

**Closed by matthewp** 2018-01-13 02:07 UTC
